package model;
// Generated Dec 25, 2017 7:47:58 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private Integer idcomments;
     private News news;
     private Users users;
     private String content;
     private Date createddate;
     private boolean status;

    public Comments() {
    }

    public Comments(News news, Users users, String content, Date createddate, boolean status) {
       this.news = news;
       this.users = users;
       this.content = content;
       this.createddate = createddate;
       this.status = status;
    }
   
    public Integer getIdcomments() {
        return this.idcomments;
    }
    
    public void setIdcomments(Integer idcomments) {
        this.idcomments = idcomments;
    }
    public News getNews() {
        return this.news;
    }
    
    public void setNews(News news) {
        this.news = news;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


