package model;
// Generated Dec 25, 2017 7:47:58 PM by Hibernate Tools 4.3.1



/**
 * Role generated by hbm2java
 */
public class Role  implements java.io.Serializable {


     private Integer idrole;
     private String rolename;
     private String description;

    public Role() {
    }

	
    public Role(String rolename) {
        this.rolename = rolename;
    }
    public Role(String rolename, String description) {
       this.rolename = rolename;
       this.description = description;
    }
   
    public Integer getIdrole() {
        return this.idrole;
    }
    
    public void setIdrole(Integer idrole) {
        this.idrole = idrole;
    }
    public String getRolename() {
        return this.rolename;
    }
    
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


