package model;
// Generated Dec 25, 2017 7:47:58 PM by Hibernate Tools 4.3.1



/**
 * Savednews generated by hbm2java
 */
public class Savednews  implements java.io.Serializable {


     private Integer idsavednews;
     private News news;
     private Users users;

    public Savednews() {
    }

    public Savednews(News news, Users users) {
       this.news = news;
       this.users = users;
    }
   
    public Integer getIdsavednews() {
        return this.idsavednews;
    }
    
    public void setIdsavednews(Integer idsavednews) {
        this.idsavednews = idsavednews;
    }
    public News getNews() {
        return this.news;
    }
    
    public void setNews(News news) {
        this.news = news;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


