package model;
// Generated Dec 25, 2017 7:47:58 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer idusers;
     private String username;
     private String email;
     private String pwd;
     private String fullname;
     private Date createddate;
     private Integer status;
     private Integer roleid;
     private String notes;
     private String avatar;
     private Set newses = new HashSet(0);
     private Set commentses = new HashSet(0);
     private Set savednewses = new HashSet(0);

    public Users() {
    }

	
    public Users(String username, String email, String pwd) {
        this.username = username;
        this.email = email;
        this.pwd = pwd;
    }
    public Users(String username, String email, String pwd, String fullname, Date createddate, Integer status, Integer roleid, String notes, String avatar, Set newses, Set commentses, Set savednewses) {
       this.username = username;
       this.email = email;
       this.pwd = pwd;
       this.fullname = fullname;
       this.createddate = createddate;
       this.status = status;
       this.roleid = roleid;
       this.notes = notes;
       this.avatar = avatar;
       this.newses = newses;
       this.commentses = commentses;
       this.savednewses = savednewses;
    }
   
    public Integer getIdusers() {
        return this.idusers;
    }
    
    public void setIdusers(Integer idusers) {
        this.idusers = idusers;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPwd() {
        return this.pwd;
    }
    
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public Date getCreateddate() {
        return this.createddate;
    }
    
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }
    public Integer getStatus() {
        return this.status;
    }
    
    public void setStatus(Integer status) {
        this.status = status;
    }
    public Integer getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    public Set getNewses() {
        return this.newses;
    }
    
    public void setNewses(Set newses) {
        this.newses = newses;
    }
    public Set getCommentses() {
        return this.commentses;
    }
    
    public void setCommentses(Set commentses) {
        this.commentses = commentses;
    }
    public Set getSavednewses() {
        return this.savednewses;
    }
    
    public void setSavednewses(Set savednewses) {
        this.savednewses = savednewses;
    }




}


